version: "3"

name: "app-dashboard-hotel-administration-dev"

services:
  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - devnet
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database-dev
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - .database-env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - devnet

volumes:
  db-data:

networks:
  devnet:
